### ISSUE TITLE
Introgression

### ISSUE THREAD

**Issue by jinshangkun** [popgenome/lettuce2020#1]
Thanks for sharing scripts! I am interested in introgresion pipline, but I can not find the Rscripts called 'introgression.filter.R' performed filtering and combine overlap region, could you send me a copy. Thanks!

**Comment by popgenome** [comment]
The script was uploaded to https://github.com/popgenome/lettuce2020/tree/master/05.demography

**Comment by jinshangkun** [comment]
Thank you very much！！！



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "popgenome/lettuce2020"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月11日(星期二) 中午11:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [popgenome/lettuce2020] Introgression (#1)





 
The script was uploaded to https://github.com/popgenome/lettuce2020/tree/master/05.demography

**Comment by popgenome** [comment]
The script is available.
