### ISSUE TITLE
MSMC2

### ISSUE THREAD

**Issue by mayufeifei28** [popgenome/lettuce2020#2]
Hi,

Thanks for sharing these very helpful codes. I am trying to look for a perl script (split_individual.pl) which was mentioned under /05.demography/06.mcmc2.sh/, but was not able to find it. It would be greatly appreciated if you could send me a copy of the perl script. 

Many thanks,

Yu

**Comment by popgenome** [comment]
The script is now available. You can do the same thing with gatk SelectVariants.
